import turtle
t=turtle.Turtle('turtle')
turtle.tracer(2)
t.up()
t.goto(0,-130)
t.down()
t.lt(45)
t.color('gold')
t.begin_fill()
for m in range (4):
    t.fd(320)
    t.lt(90)
t.end_fill()
t.left(45)
t.fd(15)
t.rt(45)
t.color('black')
t.pensize(4)

for i in range (4):
    t.fd(300)
    t.lt(90)

t.up()
t.setheading(0)
t.goto(0,-15)
t.down()
t.pensize(20)
t.circle(110,80)
position1=t.position()
angle1=t.heading()
t.up()
t.circle(110,50)
t.down()
t.circle(110,80)
position2=t.position()
angle2=t.heading()
t.up()
t.circle(110,40)
t.down()
t.circle(110,70)
position3=t.position()
angle3=t.heading()

t1=turtle.Turtle('triangle')
t1.color('black')
t1.up()
t1.shapesize(2)
t1.setposition(position1)
t1.setheading(angle1)
t1.stamp()

t1.setposition(position2)
t1.setheading(angle2)
t1.stamp()

t1.setposition(position3)
t1.setheading(angle3)


